Numpy数组（ndarray）的核心特性
多维性：支持各维度
同质性：同一个ndarray必须数据类型一致
高效性：基于连续内存块存储支持向量化运算

## 多维性

In [1]:
import numpy as np

In [8]:
arr0 = np.array(5)
print(arr0)
print('arr的维度:',arr0.ndim)  #打印arr的维度 number of dimensions


5
arr的维度: 0


In [9]:
arr1 = np.array([1, 2, 3])
print(arr1)
print('arr的维度:',arr1.ndim)

[1 2 3]
arr的维度: 1


In [13]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print('arr的维度:',arr2.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


## 同质性

In [ ]:
# 会自动把数据类型转化为一样的
arr4 = np.array([1, 'hello', 3])
print(arr4)

['1' 'hello' '3']
arr的维度: 1


In [ ]:
# 会自动把数据类型转化为一样的
arr4 = np.array([1, 2.5, 3])
print(arr4)

[1.  2.5 3. ]
arr的维度: 1


## (ndarray)的属性
![](./img/ndarray属性.png)

![](./img/属性2.png)

In [5]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3]
(3,)
3
int64


In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9.3, 4, 9]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.T)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [9.3 4.  9. ]]
(3, 3)
9
float64
[[1.  4.  9.3]
 [2.  5.  4. ]
 [3.  6.  9. ]]


## ndarry的创建方式
![](./img/构造方法.png)

### 基础构造