Numpy数组（ndarray）的核心特性
多维性：支持各维度
同质性：同一个ndarray必须数据类型一致
高效性：基于连续内存块存储支持向量化运算

## 多维性

In [1]:
import numpy as np

In [2]:
arr0 = np.array(5)
print(arr0)
print('arr的维度:',arr0.ndim)  #打印arr的维度 number of dimensions


5
arr的维度: 0


In [9]:
arr1 = np.array([1, 2, 3])
print(arr1)
print('arr的维度:',arr1.ndim)

[1 2 3]
arr的维度: 1


In [13]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print('arr的维度:',arr2.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


## 同质性

In [ ]:
# 会自动把数据类型转化为一样的
arr4 = np.array([1, 'hello', 3])
print(arr4)

['1' 'hello' '3']
arr的维度: 1


In [ ]:
# 会自动把数据类型转化为一样的
arr4 = np.array([1, 2.5, 3])
print(arr4)

[1.  2.5 3. ]
arr的维度: 1


## (ndarray)的属性
![](./img/ndarray属性.png)

![](./img/属性2.png)

In [5]:
arr = np.array([1,2,3])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[1 2 3]
(3,)
3
int64


In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
int64


In [9]:
arr2 = np.array([[1, 2, 3], [4, 5, 6],[9.3, 4, 9]])
print(arr2)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.T)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [9.3 4.  9. ]]
(3, 3)
9
float64
[[1.  4.  9.3]
 [2.  5.  4. ]
 [3.  6.  9. ]]


## ndarry的创建方式
![](./img/构造方法.png)

### 基础构造

In [13]:
# 使用列表的构造
list1 = [4, 5, 6]
arr = np.array(list1, dtype=np.float64)
print(arr.ndim)
print(arr.shape)
print(arr)

# 使用copy会复制一份出来
arr1 = np.copy(arr)
print(arr1)
arr1[0] = 6
print(arr1)
print(arr)

1
(3,)
[4. 5. 6.]
[4. 5. 6.]
[6. 5. 6.]
[4. 5. 6.]


## 预定义形状填充

In [30]:
# 全0数组
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

#全1数组
arr = np.ones((5,6),dtype=int)
print(arr)
print(arr.dtype)
print(arr.shape)

# 未初始化，随机数
arr = np.empty((3,5))
print(arr)
print(arr.dtype)
print(arr.shape)

# 用指定数字填满
arr = np.full((3,4), 2026)
print(arr)
print(arr.dtype)
print(arr.shape)


[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
int64
(5, 6)
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  6.81019663e-310]]
float64
(3, 5)
[[2026 2026 2026 2026]
 [2026 2026 2026 2026]
 [2026 2026 2026 2026]]
int64
(3, 4)


In [23]:
# 复制形状数字填充
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr,2027)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2027 2027 2027 2027]
 [2027 2027 2027 2027]
 [2027 2027 2027 2027]]


## 等差数列与等间隔序列

In [28]:
arr = np.arange(2,11,2) # 等同于range
print(arr)

arr = np.linspace(1,10,5) # 1到10取等间隔
print(arr)
arr = np.linspace(0,100,5) # 1到100取等间隔
print(arr)


# 对数间隔数列
arr = np.logspace(0 ,10, 25, base = 2) # 默认底数时10， 取等距离的数出来取对数
print(arr)

[ 2  4  6  8 10]
[ 1.    3.25  5.5   7.75 10.  ]
[  0.  25.  50.  75. 100.]
[1.00000000e+00 1.33483985e+00 1.78179744e+00 2.37841423e+00
 3.17480210e+00 4.23785238e+00 5.65685425e+00 7.55099450e+00
 1.00793684e+01 1.34543426e+01 1.79593928e+01 2.39729132e+01
 3.20000000e+01 4.27148753e+01 5.70175180e+01 7.61092554e+01
 1.01593667e+02 1.35611276e+02 1.81019336e+02 2.41631824e+02
 3.22539789e+02 4.30538965e+02 5.74700569e+02 7.67133223e+02
 1.02400000e+03]


## 特殊矩阵的构造


In [33]:
# 构建单位矩阵
arr = np.eye(3, 4, dtype=int)
print(arr)

#构建对角矩阵
arr = np.diag([5,1,2,3])  # 写主对角线的数字
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]
[[5 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]


## 随机数组的生成

In [39]:
# 随机数组的生成
# 生成0到1随机浮点数（均匀分布）
arr = np.random.rand(2,3) #2 3 为生成数组形状
print(arr)

arr = np.random.randint(3, 6, (2, 3))
print(arr)

arr = np.random.uniform(3, 6, (2, 3))
print(arr)

[[0.3963129  0.40261811 0.95306791]
 [0.90469097 0.8019279  0.71327084]]
[[5 3 5]
 [3 3 3]]
[[4.85254774 4.99209661 5.56296776]
 [5.04983252 3.78687278 5.83278657]]


In [40]:
# 符合正态分布的随机数列
arr = np.random.randn(2, 3)
print(arr)

[[-0.21704463 -1.19703295 -0.11445785]
 [-1.09930232 -1.30851143  0.13301186]]


In [43]:
# 设置随机种子

np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


![](./img/数据类型.png)

In [46]:
arr = np.array([1,0,2,0],dtype=np.bool)
print(arr)
arr = np.array([1,0,2,0],dtype=np.int8)
print(arr)
arr = np.array([1,0,2,0],dtype=np.float64)
print(arr)

[ True False  True False]
[1 0 2 0]
[1. 0. 2. 0.]
