某城市一周最高气温[28,30,29,31,32,30,29]
1. 计算平均气温，最高气温和最低气温
2. 找出气温超过30的天数

In [2]:
import numpy as np

In [6]:
arr = np.array([28,30,29,31,32,30,29])
max_day = np.argmax(arr)
min_day = np.argmin(arr)
avg_num = np.mean(arr)
print(arr[max_day],' ',arr[min_day],' ',avg_num)
print(len(arr[arr>30]))
print(np.sum(np.where(arr > 30,1,0)))


32   28   29.857142857142858
2
2


生成随机数（0，10）
矩阵（3，4）
- 计算每列最大值每行最小值
- 将数组的所有奇数替换为 -1

In [16]:
arr = np.random.randint(0, 10, size=(3, 4))
print(arr)
for i in range(4):
    print(np.max(arr[:,i]))
for i in range(3):
    print(np.min(arr[i,:]))
# 行列的最值
print(np.max(arr,axis=0))  # axis 0为行 1为列
print(np.min(arr,axis=1))
print(np.where(arr%2 != 0,-1,arr))
# 关于替换
arr[arr%2!=0] = -1
print(arr)

[[2 4 3 2]
 [0 0 7 8]
 [8 1 0 8]]
8
4
7
8
2
0
0
[8 4 7 8]
[2 0 0]
[[ 2  4 -1  2]
 [ 0  0 -1  8]
 [ 8 -1  0  8]]
[[ 2  4 -1  2]
 [ 0  0 -1  8]
 [ 8 -1  0  8]]
