# ndarray操作函数和方法

## 索引与切片

![](./img/索引与切片.png)

### 一维数组的索引与切片

In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[3:9])   #左闭右开
print(arr[arr>10])   #布尔索引
print(arr[(arr>10) & (arr<70)]) #逻辑链接
print(arr[slice(2,15,2)])

[38 50 24 74 28 86 63  6 97 31  9 66  8 85  9 37 53 10 90 38]
38
[74 28 86 63  6 97]
[38 50 24 74 28 86 63 97 31 66 85 37 53 90 38]
[38 50 24 28 63 31 66 37 53 38]
[24 28 63 97  9  8  9]


### 二维数组

In [14]:
arr = np.random.randint(1,100,(4,5))
print(arr)
print(arr[1,2])
print(arr[1,:])
print(arr[:,:])

# 有区别的时布尔索引
print(arr[arr>50]) # 打印为一维结果
print(arr[2][arr[2]>50])
print(arr[:,3][arr[:,3]>20])

[[47 53 71 34 53]
 [18 91  1  7 52]
 [99 81 54 67 23]
 [39 33 35  4 25]]
1
[18 91  1  7 52]
[[47 53 71 34 53]
 [18 91  1  7 52]
 [99 81 54 67 23]
 [39 33 35  4 25]]
[53 71 53 91 52 99 81 54 67]
[99 81 54 67]
[34 67]


## ndarray运算

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(b - a)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(b - a)
print(a * b)
print(a / b)
print(a ** 2)
print(a+3)  # 每一个元素加3
print(a*3)  # 每一个数组×三

### 广播机制


In [20]:
# 同一纬度 相同或者为1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)
print(b-a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


### 矩阵运算

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b)
print(np.dot(a,b))

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


## numpy常用函数

### 基本数学函数 

In [17]:
# 计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
# 计算指数
print(np.exp(1))
# 计算自然对数
print(np.log(2.7182))
# 计算三角函数的值
print(np.sin(1))
print(np.cos(np.pi))
# 计算绝对值
arr = np.array([5,6,-8,-9,-7,-7])
print(np.abs(arr))
# 计算a的b次幂
print(np.power(arr,2))
# 四舍五入
print(np.round([3.2,4.51,8.1,9.2]))
# 向上取整向下取整
arr = np.array([3.2,4.51,8.1,9.2])
print(np.ceil(arr))
print(np.floor(arr))
# 检测缺失值 is Nan
np.isnan([4,np.nan,6])

3.0
[1. 2. 3.]
2.718281828459045
0.9999698965391098
0.8414709848078965
-1.0
[5 6 8 9 7 7]
[25 36 64 81 49 49]
[3. 5. 8. 9.]
[ 4.  5.  9. 10.]
[3. 4. 8. 9.]


array([False,  True, False])

### 基本统计函数

In [ ]:
# 求和，  平均，    中位数，     标准差，   方差
# np.sum  np.mean  np.median    np.std   np.var
# 最大值， 索引       最小值， 最小值索引   分位数，(两个参数，50%是中位数)
# np.max  np.argmax  np.min  np.argmin   np.percentile
# 累积  (得数组)   累和
# np.cum      np.sum


### 比较函数
比较是否为大于、小于、等于 逻辑与或非，检查数组中是否有一个True，是否都为True ，自定义条件

In [20]:
# 注意广播机制的体现
# 是否大于4
print(np.greater([3,4,5,6,7],4))
# 是否小于4
print(np.less([3,4,5,6,7],4))
# 是否等于
print(np.equal([3,4,5,6,7],4))
print(np.equal([3,4,5],[4,4,4]))
# 逻辑与或非
print(np.logical_and([1,0],[1,1]))
print(np.logical_or([1,0],[1,1]))
print(np.logical_not([1,0]))

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[False  True False]
[ True False]
[ True  True]
[False  True]


In [36]:
# 自定义条件
# print(np.where(条件，符合条件的，不符合条件的))
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0)) #可以很好的对数据分类

# 例子
score = np.random.randn(3,4) * 10 + 65
print(score)
print(np.where(score < 60,'不及格','及格'))
print(np.where(score < 60,'不及格',
               np.where(score>80,'优秀','良好')))
# np.select(条件，返回值)
print(np.select([score<60,(score>=60) & (score<80),
                 score>=80],['不及格','及格','优秀'],default='未知'))

[1 2 0 0 0]
[[62.97757889 64.38514573 69.85713484 63.96885289]
 [60.38954192 67.67647985 60.14554542 66.8252355 ]
 [67.70044907 81.53042975 59.53025888 65.01238841]]
[['及格' '及格' '及格' '及格']
 ['及格' '及格' '及格' '及格']
 ['及格' '及格' '不及格' '及格']]
[['良好' '良好' '良好' '良好']
 ['良好' '良好' '良好' '良好']
 ['良好' '优秀' '不及格' '良好']]
[['及格' '及格' '及格' '及格']
 ['及格' '及格' '及格' '及格']
 ['及格' '优秀' '不及格' '及格']]


### 排序函数

In [ ]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
# 两种用法，一种改变原来一种不改变
print(arr)
print(np.sort(arr))
print(arr)
print(arr.sort())
print(arr)
# 返回索引
print(np.argsort(arr))
print(arr.argsort())
print(arr)
# 去重函数
print(np.unique(arr))
print(arr)
# print(arr.unique()) 不可用

# 两个数组的拼接
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1,arr2)))

# 数组的分割
print(np.split(arr,[6,12,18])) # 后面数字为索引
# 重新调整形状
print(np.reshape(arr,[4,5]))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
None
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[1 2 3 4 5 6]
[array([10, 13, 22, 37, 40, 45], dtype=int32), array([47, 48, 59, 65, 66, 68], dtype=int32), array([68, 71, 84, 88, 88, 89], dtype=int32), array([89, 89], dtype=int32)]
[[10 13 22 37 40]
 [45 47 48 59 65]
 [66 68 68 71 84]
 [88 88 89 89 89]]
