# ndarray操作函数和方法

## 索引与切片

![](./img/索引与切片.png)

### 一维数组的索引与切片

In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,100,20)
print(arr)
print(arr[0])
print(arr[3:9])   #左闭右开
print(arr[arr>10])   #布尔索引
print(arr[(arr>10) & (arr<70)]) #逻辑链接
print(arr[slice(2,15,2)])

[38 50 24 74 28 86 63  6 97 31  9 66  8 85  9 37 53 10 90 38]
38
[74 28 86 63  6 97]
[38 50 24 74 28 86 63 97 31 66 85 37 53 90 38]
[38 50 24 28 63 31 66 37 53 38]
[24 28 63 97  9  8  9]


### 二维数组

In [14]:
arr = np.random.randint(1,100,(4,5))
print(arr)
print(arr[1,2])
print(arr[1,:])
print(arr[:,:])

# 有区别的时布尔索引
print(arr[arr>50]) # 打印为一维结果
print(arr[2][arr[2]>50])
print(arr[:,3][arr[:,3]>20])

[[47 53 71 34 53]
 [18 91  1  7 52]
 [99 81 54 67 23]
 [39 33 35  4 25]]
1
[18 91  1  7 52]
[[47 53 71 34 53]
 [18 91  1  7 52]
 [99 81 54 67 23]
 [39 33 35  4 25]]
[53 71 53 91 52 99 81 54 67]
[99 81 54 67]
[34 67]


## ndarray运算

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(b - a)
print(a * b)
print(a / b)
print(a ** 2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a + b)
print(b - a)
print(a * b)
print(a / b)
print(a ** 2)
print(a+3)  # 每一个元素加3
print(a*3)  # 每一个数组×三

### 广播机制


In [20]:
# 同一纬度 相同或者为1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)
print(b-a)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[3 2 1]
 [4 3 2]
 [5 4 3]]


### 矩阵运算

In [21]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a @ b)

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


## numpy常用函数

In [22]:
## 基本数学函数